export enum ActionAction {
    CREATED = "CREATED",
    ASSIGNED = "ASSIGNED",
    MOVED = "MOVED",
    UPDATED = "UPDATED",
    COMMENTED = "COMMENTED",
    DELETED = "DELETED",
    EDITED = "EDITED",
    EMAIL_SENT = "EMAIL_SENT",
    NOTIFICATION_SENT = "NOTIFICATION_SENT",
}
