export enum HOTEL_PERMISSION_ENUM {
    CREATE_BOOKING = "CREATE_BOOKING",
    READ_BOOKING = "READ_BOOKING",
    UPDATE_BOOKING = "UPDATE_BOOKING",
    CANCEL_BOOKING = "CANCEL_BOOKING",

    // ROOMS
    CREATE_ROOM = "CREATE_ROOM",
    READ_ROOM = "READ_ROOM",
    UPDATE_ROOM = "UPDATE_ROOM",
    DELETE_ROOM = "DELETE_ROOM",

    // CUSTOMERS
    CREATE_CUSTOMER = "CREATE_CUSTOMER",
    READ_CUSTOMER = "READ_CUSTOMER",
    UPDATE_CUSTOMER = "UPDATE_CUSTOMER",
    DELETE_CUSTOMER = "DELETE_CUSTOMER",

    // ROOM_TYPES
    CREATE_ROOM_TYPE = "CREATE_ROOM_TYPE",
    READ_ROOM_TYPE = "READ_ROOM_TYPE",
    UPDATE_ROOM_TYPE = "UPDATE_ROOM_TYPE",
    DELETE_ROOM_TYPE = "DELETE_ROOM_TYPE",
}

export enum HOTEL_PERMISSION_GROUP {
    BOOKING = "BOOKING",
    ROOMS = "ROOMS",
    CUSTOMERS = "CUSTOMERS",
    ROOM_TYPES = "ROOM_TYPES",
}

export const HOTEL_DEFAULT_ROLES = {
    ADMIN: {
        role: "ADMIN",
        permissions: [
            HOTEL_PERMISSION_ENUM.CREATE_BOOKING,
            HOTEL_PERMISSION_ENUM.READ_BOOKING,
            HOTEL_PERMISSION_ENUM.UPDATE_BOOKING,
            HOTEL_PERMISSION_ENUM.CANCEL_BOOKING,

            HOTEL_PERMISSION_ENUM.CREATE_ROOM,
            HOTEL_PERMISSION_ENUM.READ_ROOM,
            HOTEL_PERMISSION_ENUM.UPDATE_ROOM,
            HOTEL_PERMISSION_ENUM.DELETE_ROOM,

            HOTEL_PERMISSION_ENUM.CREATE_CUSTOMER,
            HOTEL_PERMISSION_ENUM.READ_CUSTOMER,
            HOTEL_PERMISSION_ENUM.UPDATE_CUSTOMER,
            HOTEL_PERMISSION_ENUM.DELETE_CUSTOMER,

            HOTEL_PERMISSION_ENUM.CREATE_ROOM_TYPE,
            HOTEL_PERMISSION_ENUM.READ_ROOM_TYPE,
            HOTEL_PERMISSION_ENUM.UPDATE_ROOM_TYPE,
            HOTEL_PERMISSION_ENUM.DELETE_ROOM_TYPE,
        ],
    },
    RECEPTIONIST: {
        role: "RECEPTIONIST",
        permissions: [
            HOTEL_PERMISSION_ENUM.CREATE_BOOKING,
            HOTEL_PERMISSION_ENUM.READ_BOOKING,
            HOTEL_PERMISSION_ENUM.UPDATE_BOOKING,
            HOTEL_PERMISSION_ENUM.CANCEL_BOOKING,

            HOTEL_PERMISSION_ENUM.READ_ROOM,

            HOTEL_PERMISSION_ENUM.CREATE_CUSTOMER,
            HOTEL_PERMISSION_ENUM.READ_CUSTOMER,
            HOTEL_PERMISSION_ENUM.UPDATE_CUSTOMER,

            HOTEL_PERMISSION_ENUM.READ_ROOM_TYPE,
        ],
    },
    HOUSEKEEPING: {
        role: "HOUSEKEEPING",
        permissions: [
            HOTEL_PERMISSION_ENUM.READ_BOOKING,

            HOTEL_PERMISSION_ENUM.READ_ROOM,

            HOTEL_PERMISSION_ENUM.READ_CUSTOMER,

            HOTEL_PERMISSION_ENUM.READ_ROOM_TYPE,
        ],
    },
};
