export enum PERMISSION_ENUM {
    // PROJECT
    CREATE_PROJECT = "CREATE_PROJECT",
    READ_PROJECT = "READ_PROJECT",
    UPDATE_PROJECT = "UPDATE_PROJECT",
    DELETE_PROJECT = "DELETE_PROJECT",
    // TASK
    CREATE_TASK = "CREATE_TASK",
    READ_TASK = "READ_TASK",
    UPDATE_TASK = "UPDATE_TASK",
    DELETE_TASK = "DELETE_TASK",

    // CUSTOMERS
    CREATE_CUSTOMER = "CREATE_CUSTOMER",
    READ_CUSTOMER = "READ_CUSTOMER",
    UPDATE_CUSTOMER = "UPDATE_CUSTOMER",
    DELETE_CUSTOMER = "DELETE_CUSTOMER",

    // EXTRA
    // AUDIT LOGS
    READ_AUDIT_LOGS = "READ_AUDIT_LOGS",
    // DASHBOARD
    READ_DASHBOARD = "READ_DASHBOARD",

    // LABELS
    CREATE_LABEL = "CREATE_LABEL",
    READ_LABEL = "READ_LABEL",
    UPDATE_LABEL = "UPDATE_LABEL",
    DELETE_LABEL = "DELETE_LABEL",

    // TASK_STATUS
    CREATE_TASK_STATUS = "CREATE_TASK_STATUS",
    READ_TASK_STATUS = "READ_TASK_STATUS",
    UPDATE_TASK_STATUS = "UPDATE_TASK_STATUS",
    DELETE_TASK_STATUS = "DELETE_TASK_STATUS",

    // SPRINTS
    CREATE_SPRINT = "CREATE_SPRINT",
    READ_SPRINT = "READ_SPRINT",
    UPDATE_SPRINT = "UPDATE_SPRINT",
    DELETE_SPRINT = "DELETE_SPRINT",

    // ! SUPER ADMIN ONLY
    // EMPLOYEE
    CREATE_EMPLOYEE = "CREATE_EMPLOYEE",
    READ_EMPLOYEE = "READ_EMPLOYEE",
    READ_EMPLOYEE_DETAILS = "READ_EMPLOYEE_DETAILS",
    UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE",
    DELETE_EMPLOYEE = "DELETE_EMPLOYEE",
    // ROLES
    CREATE_ROLE = "CREATE_ROLE",
    READ_ROLE = "READ_ROLE",
    UPDATE_ROLE = "UPDATE_ROLE",
    DELETE_ROLE = "DELETE_ROLE",

    // PERMISSIONS
    // CREATE_PERMISSION = "CREATE_PERMISSION",
    // READ_PERMISSION = "READ_PERMISSION",
    // UPDATE_PERMISSION = "UPDATE_PERMISSION",
    // DELETE_PERMISSION = "DELETE_PERMISSION",

    // FEATURES
    CREATE_FEATURE = "CREATE_FEATURE",
    READ_FEATURE = "READ_FEATURE",
    UPDATE_FEATURE = "UPDATE_FEATURE",
    DELETE_FEATURE = "DELETE_FEATURE",

    // COMPANY
    CREATE_INTERNAL_COMPANY = "CREATE_INTERNAL_COMPANY",
    READ_INTERNAL_COMPANY = "READ_INTERNAL_COMPANY",
    UPDATE_INTERNAL_COMPANY = "UPDATE_INTERNAL_COMPANY",
    DELETE_INTERNAL_COMPANY = "DELETE_INTERNAL_COMPANY",
}

export enum ROLE_TYPE {
    SUPER_ADMIN = "SUPER_ADMIN",
    COMPANY_ADMIN = "COMPANY_ADMIN",
    FEATURE_MANAGER = "FEATURE_MANAGER",
    EMPLOYEE = "EMPLOYEE",
}

export enum ROLE_LEVEL {
    SUPER_ADMIN = 5,
    COMPANY_ADMIN = 4,
    FEATURE_MANAGER = 3,
    EMPLOYEE = 2,
    CUSTOMER = 0,
    THIRD_PARTY = 1,
}

export enum PERMISSION_TYPE {
    NORMAL = "NORMAL",
    NORMAL_SETTINGS = "NORMAL_SETTINGS",
    COMPANY_SETTINGS = "COMPANY_SETTINGS",
    SUPER_ADMIN_SETTINGS = "SUPER_ADMIN_SETTINGS",
}

export enum PERMISSION_GROUP {
    PROJECTS = "PROJECTS",
    TASKS = "TASKS",
    CUSTOMERS = "CUSTOMERS",
    EXTRA = "EXTRA",
    EMPLOYEES = "EMPLOYEES",
    ROLES = "ROLES",
    PERMISSIONS = "PERMISSIONS",
    FEATURES = "FEATURES",
    COMPANY = "COMPANY",
}

export const DEFAULT_ROLES = {
    SUPER_ADMIN: {
        role: "SUPER_ADMIN",
        permissions: [
            // PROJECT
            PERMISSION_ENUM.CREATE_PROJECT,
            PERMISSION_ENUM.READ_PROJECT,
            PERMISSION_ENUM.UPDATE_PROJECT,
            PERMISSION_ENUM.DELETE_PROJECT,
            // TASK
            PERMISSION_ENUM.CREATE_TASK,
            PERMISSION_ENUM.READ_TASK,
            PERMISSION_ENUM.UPDATE_TASK,
            PERMISSION_ENUM.DELETE_TASK,

            // CUSTOMERS
            PERMISSION_ENUM.CREATE_CUSTOMER,
            PERMISSION_ENUM.READ_CUSTOMER,
            PERMISSION_ENUM.UPDATE_CUSTOMER,
            PERMISSION_ENUM.DELETE_CUSTOMER,

            // EXTRA
            // AUDIT LOGS
            PERMISSION_ENUM.READ_AUDIT_LOGS,
            // DASHBOARD
            PERMISSION_ENUM.READ_DASHBOARD,

            // LABELS
            PERMISSION_ENUM.CREATE_LABEL,
            PERMISSION_ENUM.READ_LABEL,
            PERMISSION_ENUM.UPDATE_LABEL,
            PERMISSION_ENUM.DELETE_LABEL,

            // TASK_STATUS
            PERMISSION_ENUM.CREATE_TASK_STATUS,
            PERMISSION_ENUM.READ_TASK_STATUS,
            PERMISSION_ENUM.UPDATE_TASK_STATUS,
            PERMISSION_ENUM.DELETE_TASK_STATUS,
        ],
    },
    COMPANY_ADMIN: {
        role: "COMPANY_ADMIN",
        permissions: [
            // PROJECT
            PERMISSION_ENUM.CREATE_PROJECT,
            PERMISSION_ENUM.READ_PROJECT,
            PERMISSION_ENUM.UPDATE_PROJECT,
            PERMISSION_ENUM.DELETE_PROJECT,
            // TASK
            PERMISSION_ENUM.CREATE_TASK,
            PERMISSION_ENUM.READ_TASK,
            PERMISSION_ENUM.UPDATE_TASK,
            PERMISSION_ENUM.DELETE_TASK,

            // CUSTOMERS
            PERMISSION_ENUM.CREATE_CUSTOMER,
            PERMISSION_ENUM.READ_CUSTOMER,
            PERMISSION_ENUM.UPDATE_CUSTOMER,
            PERMISSION_ENUM.DELETE_CUSTOMER,

            // EXTRA
            // AUDIT LOGS
            PERMISSION_ENUM.READ_AUDIT_LOGS,
            // DASHBOARD
            PERMISSION_ENUM.READ_DASHBOARD,

            // LABELS
            PERMISSION_ENUM.CREATE_LABEL,
            PERMISSION_ENUM.READ_LABEL,
            PERMISSION_ENUM.UPDATE_LABEL,
            PERMISSION_ENUM.DELETE_LABEL,

            // TASK_STATUS
            PERMISSION_ENUM.CREATE_TASK_STATUS,
            PERMISSION_ENUM.READ_TASK_STATUS,
            PERMISSION_ENUM.UPDATE_TASK_STATUS,
            PERMISSION_ENUM.DELETE_TASK_STATUS,

            // EMPLOYEE
            PERMISSION_ENUM.CREATE_EMPLOYEE,
            PERMISSION_ENUM.READ_EMPLOYEE,
            PERMISSION_ENUM.READ_EMPLOYEE_DETAILS,
            PERMISSION_ENUM.UPDATE_EMPLOYEE,
            PERMISSION_ENUM.DELETE_EMPLOYEE,
        ],
    },
};
