export enum PERMISSION_ENUM {
    // COMPANY
    CREATE_INTERNAL_COMPANY = "CREATE_INTERNAL_COMPANY",
    READ_INTERNAL_COMPANY = "READ_INTERNAL_COMPANY",
    UPDATE_INTERNAL_COMPANY = "UPDATE_INTERNAL_COMPANY",
    DELETE_INTERNAL_COMPANY = "DELETE_INTERNAL_COMPANY",
    // PROJECT
    CREATE_PROJECT = "CREATE_PROJECT",
    READ_PROJECT = "READ_PROJECT",
    UPDATE_PROJECT = "UPDATE_PROJECT",
    DELETE_PROJECT = "DELETE_PROJECT",
    // TASK
    CREATE_TASK = "CREATE_TASK",
    READ_TASK = "READ_TASK",
    UPDATE_TASK = "UPDATE_TASK",
    DELETE_TASK = "DELETE_TASK",
    // USERS
    CREATE_USER = "CREATE_USER",
    READ_USER = "READ_USER",
    UPDATE_USER = "UPDATE_USER",
    DELETE_USER = "DELETE_USER",
    // EMPLOYEE
    CREATE_EMPLOYEE = "CREATE_EMPLOYEE",
    READ_EMPLOYEE = "READ_EMPLOYEE",
    UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE",
    DELETE_EMPLOYEE = "DELETE_EMPLOYEE",
    // LABELS
    CREATE_LABEL = "CREATE_LABEL",
    READ_LABEL = "READ_LABEL",
    UPDATE_LABEL = "UPDATE_LABEL",
    DELETE_LABEL = "DELETE_LABEL",
}
