export enum PERMISSION_ENUM {
    CREATE_EMPLOYEE = "CREATE_EMPLOYEE",
    READ_EMPLOYEE = "READ_EMPLOYEE",
    UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE",
    DELETE_EMPLOYEE = "DELETE_EMPLOYEE",
    // LABELS
    CREATE_LABEL = "CREATE_LABEL",
    READ_LABEL = "READ_LABEL",
    UPDATE_LABEL = "UPDATE_LABEL",
    DELETE_LABEL = "DELETE_LABEL",
}
