name: CI/CD Pipeline - Project Management App

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Backend Docker build & push
            - name: Build and Push Backend Image
              uses: docker/build-push-action@v6
              with:
                  context: ./server
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/pma-backend:latest

            # Frontend Docker build & push
            - name: Build and Push Frontend Image
              uses: docker/build-push-action@v6
              with:
                  context: ./frontend
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/pma-frontend:latest

    deploy:
        needs: build
        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Log in to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Pull Latest Images
              run: |
                  docker compose pull

            - name: Restart Services
              run: |
                  docker compose up -d --remove-orphans
